services:
  mysql_db:
    image: mysql:8.0
    hostname: mysql_db
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 20
    # volumes:
    #   - mysql_data:/var/lib/mysql
    # logging:
    #   options:
    #     max-size: "10m"
    #     max-file: "3"
  server:
    build: 
      context: server  
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '8000:8000'
    volumes:
     - ./server:/app
    stdin_open: true
    tty: true  # Keeps the container running for debugging
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - prisma-network

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - prisma-network
    stdin_open: true
    tty: true
     # Add this line to explicitly run vite:
    command: npm run dev -- --host 0.0.0.0

networks:
    prisma-network:
      name: prisma-network
